import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const supabase=createClient("https://c--09586474-253e-4035-b48c-481591adc286-prod.lovable.cloud","sb_publishable_4zkSUbnHOH5kawdNM3d6lQ_xd5Do3bb");
const br=n=>Number(n||0).toLocaleString('pt-BR');
const esc=s=>String(s??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=d=>new Date(d).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'});
const fmtTime=d=>new Date(d).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});

if(location.pathname.toLowerCase().replace(/\/+$/,'')==='/admin'){
 const st=document.createElement('style');st.textContent=`
 .admin-head{position:relative!important;min-height:150px!important}
 .admin-head h1{font-size:31px!important;margin:6px 0!important;color:#5d4038!important}
 .admin-head p{font-size:14px!important}
 .hub-head-meta,.hub-profile,.hub-date{display:none!important}
 .hub-slogan{position:absolute;right:28%;top:47px;color:#b36b5c;font-family:Georgia,serif;font-style:italic;font-size:25px;line-height:1.05;transform:rotate(-4deg);text-align:center;opacity:.95;pointer-events:none}
 .hub-slogan span{display:block}
 .hub-extra{display:grid;grid-template-columns:1.05fr 1fr;gap:14px;margin-top:14px}
 .hub-panel{background:#fff;border:1px solid #eaded9;border-radius:18px;padding:20px;box-shadow:0 5px 18px #70483c08;min-width:0}
 .hub-panel-head{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:14px}.hub-panel-head h2{margin:0;font-size:18px;color:#65453e}.hub-range{border:1px solid #eaded9;border-radius:10px;padding:8px 11px;font-size:11px;color:#72564e;background:#fffaf8;white-space:nowrap}
 .hub-chart{height:250px;display:flex;align-items:flex-end;gap:16px;padding:20px 12px 28px;border-top:1px solid #f3ebe7;position:relative}.hub-chart:before{content:'';position:absolute;left:12px;right:12px;top:28%;border-top:1px solid #f2e8e4;box-shadow:0 57px 0 #f2e8e4,0 114px 0 #f2e8e4}.hub-bar-wrap{flex:1;height:100%;display:flex;align-items:center;justify-content:flex-end;flex-direction:column;position:relative;z-index:1}.hub-bar{width:100%;max-width:54px;background:linear-gradient(180deg,#bf7c6a,#cf9a88);border-radius:5px 5px 0 0;min-height:4px}.hub-day{font-size:11px;color:#8a7973;margin-top:9px}.hub-bar-val{font-size:10px;color:#8e6258;margin-bottom:5px;font-weight:800}
 .hub-moves{overflow:auto}.hub-moves table{width:100%;border-collapse:collapse}.hub-moves th{background:#f3eeeb;color:#81716b;text-align:left;font-size:10px;padding:9px}.hub-moves td{padding:10px 9px;border-bottom:1px solid #f0e7e3;font-size:11px;white-space:nowrap}.hub-tag{display:inline-block;padding:5px 9px;border-radius:999px;font-size:10px;font-weight:800}.hub-tag.out{background:#fae6de;color:#b1604e}.hub-tag.in{background:#e6f3e9;color:#3a7651}.hub-more{text-align:right;margin-top:11px;color:#a85f52;font-size:11px;font-weight:800}
 @media(max-width:1100px){.hub-extra{grid-template-columns:1fr}.hub-slogan{right:19%}}@media(max-width:760px){.hub-slogan{display:none}.hub-chart{gap:7px}.hub-bar{max-width:34px}}
 `;document.head.appendChild(st);

 function fixHeader(){const h=document.querySelector('.admin-head');if(!h)return;h.querySelectorAll('.hub-head-meta,.hub-profile,.hub-date').forEach(x=>x.remove());const h1=h.querySelector('h1');if(h1)h1.textContent='Painel Administrativo';const p=h.querySelector('p');if(p)p.textContent='Acompanhe estoque, retiradas, inventários, consumo e compras.';if(!h.querySelector('.hub-slogan')){const s=document.createElement('div');s.className='hub-slogan';s.innerHTML='<span>Disciplina</span><span>gera resultado ♡</span>';h.appendChild(s)}}

 async function addExtra(){const pane=document.querySelector('[data-pane="resumo"]');if(!pane||pane.querySelector('.hub-extra')||pane.dataset.extraLoading==='1')return;pane.dataset.extraLoading='1';const [rr,ee]=await Promise.all([supabase.from('retiradas').select('*').order('created_at',{ascending:false}),supabase.from('entradas_estoque').select('*').order('created_at',{ascending:false})]);pane.dataset.extraLoading='';if(rr.error||ee.error)return;const rows=rr.data||[],ents=ee.data||[];const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);const k=d.toLocaleDateString('en-CA'),label=d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}),value=rows.filter(r=>String(r.created_at||'').slice(0,10)===k).reduce((a,r)=>a+Number(r.total_caixas||0),0);days.push({label,value})}const max=Math.max(1,...days.map(x=>x.value));const moves=[...rows.slice(0,12).map(r=>({date:r.created_at,type:'Retirada',box:r.tipo_caixa,qty:r.total_caixas,user:r.responsavel||'—',obs:'Retirada registrada'})),...ents.slice(0,12).map(e=>({date:e.created_at,type:'Entrada',box:e.tipo_caixa,qty:e.total_caixas,user:'Larissa',obs:e.observacao||'Entrada de estoque'}))].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,6);const extra=document.createElement('div');extra.className='hub-extra';extra.innerHTML=`<div class="hub-panel"><div class="hub-panel-head"><h2>Consumo de caixas — últimos 7 dias</h2><span class="hub-range">Últimos 7 dias</span></div><div class="hub-chart">${days.map(d=>`<div class="hub-bar-wrap"><div class="hub-bar-val">${d.value||''}</div><div class="hub-bar" style="height:${Math.max(2,d.value/max*88)}%"></div><div class="hub-day">${d.label}</div></div>`).join('')}</div></div><div class="hub-panel hub-moves"><div class="hub-panel-head"><h2>Últimas movimentações</h2></div><table><thead><tr><th>DATA/HORA</th><th>TIPO</th><th>CAIXA</th><th>QUANTIDADE</th><th>USUÁRIO</th><th>OBSERVAÇÃO</th></tr></thead><tbody>${moves.map(m=>`<tr><td>${fmtDate(m.date)} ${fmtTime(m.date)}</td><td><span class="hub-tag ${m.type==='Entrada'?'in':'out'}">${m.type}</span></td><td>${esc(m.box)}</td><td>${br(m.qty)}</td><td>${esc(m.user)}</td><td>${esc(m.obs)}</td></tr>`).join('')||'<tr><td colspan="6">Nenhuma movimentação.</td></tr>'}</tbody></table><div class="hub-more">Movimentações recentes</div></div>`;pane.appendChild(extra)}
 const run=()=>{fixHeader();addExtra()};
 const ob=new MutationObserver(()=>requestAnimationFrame(run));ob.observe(document.body,{childList:true,subtree:true});addEventListener('DOMContentLoaded',run);setTimeout(run,150);setTimeout(run,700);
}
