import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const supabase=createClient("https://c--09586474-253e-4035-b48c-481591adc286-prod.lovable.cloud","sb_publishable_4zkSUbnHOH5kawdNM3d6lQ_xd5Do3bb");
const BASE={PP:1575,P:5550,M:1200};
const br=n=>Number(n||0).toLocaleString('pt-BR');
const esc=s=>String(s??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=d=>new Date(d).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'});
const fmtTime=d=>new Date(d).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});
const todayKey=()=>new Date().toLocaleDateString('en-CA');
const monthKey=()=>new Date().toLocaleDateString('en-CA',{year:'numeric',month:'2-digit'});

if(location.pathname.toLowerCase().replace(/\/+$/,'')==='/admin'){
 const st=document.createElement('style');st.textContent=`
 .admin-wrap{padding-left:248px!important;background:#f8f3f0!important}.admin-shell{max-width:none!important}
 .admin-head{min-height:220px!important;padding:34px 38px 26px!important;margin:0 -28px 18px!important;background:linear-gradient(120deg,#fbf2ee 0%,#f5e4de 54%,#fffaf7 100%)!important;position:relative;overflow:hidden;align-items:flex-start!important}
 .admin-head:before{content:'';position:absolute;inset:0;background:repeating-radial-gradient(ellipse at 38% 100%,transparent 0 12px,#dcb8ac22 13px 14px,transparent 15px 28px);opacity:.7;pointer-events:none}
 .admin-head>div{position:relative;z-index:1}.admin-kicker{color:#a85f52!important;font-size:12px!important;letter-spacing:.18em!important}.admin-head h1{font-size:42px!important;line-height:1!important;color:#2e2927!important;margin:10px 0 8px!important}.admin-head p{font-size:15px!important;color:#726661!important}
 .admin-actions{position:relative;z-index:2;display:grid!important;grid-template-columns:auto auto;gap:10px!important;align-items:center!important}.admin-actions .ghost-btn{background:#fffaf7!important;border:1px solid #c98776!important;color:#8e4f43!important;border-radius:12px!important;padding:12px 18px!important;box-shadow:0 4px 12px #7c4d4210}.admin-actions .ghost-btn:first-of-type{background:#b86655!important;color:#fff!important;border-color:#b86655!important}
 .hub-head-meta{grid-column:1/-1;display:flex;justify-content:flex-end;gap:12px;align-items:center;margin-bottom:8px}.hub-date{background:#fff;border:1px solid #eee1dc;border-radius:999px;padding:10px 15px;font-size:12px;font-weight:700;color:#5d514d;box-shadow:0 5px 16px #70483c0b}.hub-profile{display:flex;align-items:center;gap:9px;padding:6px 2px}.hub-avatar{width:34px;height:34px;border-radius:50%;background:#a85f52;color:#fff;display:grid;place-items:center;font-weight:900}.hub-profile b,.hub-profile small{display:block}.hub-profile b{font-size:12px}.hub-profile small{font-size:10px;color:#8a7771}
 .hub-slogan{position:absolute;right:34%;top:88px;z-index:1;color:#b36b5c;font-family:Georgia,serif;font-style:italic;font-size:25px;line-height:1.05;transform:rotate(-5deg);text-align:center;opacity:.95}.hub-slogan span{display:block}
 .tabs{width:248px!important;padding:22px 14px!important}.tabs:after{content:'CAIXAS HUB EASY · CONTROLE OPERACIONAL'!important;margin-top:42px!important}.tabs:before{font-size:36px!important;padding-top:0!important}
 .tab{position:relative;padding:13px 14px 13px 42px!important;font-size:14px!important}.tab:before{position:absolute;left:15px;top:50%;transform:translateY(-50%);font-size:15px;color:#9a6a60;font-weight:400}.tab[data-tab='resumo']:before{content:'⌂'}.tab[data-tab='retiradas']:before{content:'▣'}.tab[data-tab='entradas']:before{content:'◇'}.tab[data-tab='inventario']:before{content:'▥'}.tab[data-tab='consumo']:before{content:'▥'}.tab[data-tab='compras']:before{content:'▤'}.tab[data-tab='relatorios']:before{content:'▤'}#custosCaixasTab:before{content:'$'}.tab.active{background:#f0dfd9!important;color:#8f5045!important}
 .hub-summary{display:grid;gap:16px}.hub-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.hub-kpi{background:#fff;border:1px solid #eaded9;border-radius:14px;padding:17px 18px;display:grid;grid-template-columns:52px 1fr;gap:14px;align-items:center;box-shadow:0 6px 20px #70483c0b}.hub-kpi-icon{width:48px;height:48px;border-radius:50%;background:#f5e6e0;color:#ad6254;display:grid;place-items:center;font-size:24px}.hub-kpi span{display:block;font-size:12px;color:#625754}.hub-kpi strong{display:block;font-size:30px;line-height:1.05;color:#171515;margin:3px 0}.hub-kpi small{display:block;font-size:10px;color:#8b7973}.hub-kpi .up{color:#2f9d59;font-weight:800}.hub-kpi .down{color:#d36b4d;font-weight:800}
 .hub-summary-grid{display:grid;grid-template-columns:1.08fr 1fr;gap:16px}.hub-panel{background:#fff;border:1px solid #eaded9;border-radius:14px;padding:18px;box-shadow:0 6px 20px #70483c0a}.hub-panel-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.hub-panel-head h2{margin:0;font-size:19px;color:#222}.hub-range{border:1px solid #eaded9;border-radius:10px;padding:8px 12px;font-size:11px;color:#72564e;background:#fffaf8}
 .hub-chart{height:245px;display:flex;align-items:flex-end;gap:18px;padding:24px 14px 30px;border-top:1px solid #f3ebe7;position:relative}.hub-chart:before{content:'';position:absolute;left:14px;right:14px;top:25%;border-top:1px solid #f2e8e4;box-shadow:0 58px 0 #f2e8e4,0 116px 0 #f2e8e4}.hub-bar-wrap{flex:1;height:100%;display:flex;align-items:flex-end;justify-content:flex-end;flex-direction:column;position:relative;z-index:1}.hub-bar{width:100%;max-width:54px;margin:auto;background:linear-gradient(180deg,#bf7c6a,#cf9a88);border-radius:4px 4px 0 0;min-height:4px}.hub-day{width:100%;text-align:center;font-size:11px;color:#8a7973;margin-top:9px}.hub-bar-val{width:100%;text-align:center;font-size:10px;color:#8e6258;margin-bottom:5px;font-weight:800}
 .hub-moves table{width:100%;border-collapse:collapse}.hub-moves th{background:#f3eeeb;color:#81716b;text-align:left;font-size:10px;padding:9px}.hub-moves td{padding:10px 9px;border-bottom:1px solid #f0e7e3;font-size:11px;white-space:nowrap}.hub-tag{display:inline-block;padding:5px 10px;border-radius:999px;font-size:10px;font-weight:800}.hub-tag.out{background:#fae6de;color:#b1604e}.hub-tag.in{background:#e6f3e9;color:#3a7651}.hub-more{text-align:right;margin-top:11px;color:#a85f52;font-size:11px;font-weight:800}
 @media(max-width:1100px){.hub-kpis{grid-template-columns:1fr 1fr}.hub-summary-grid{grid-template-columns:1fr}.hub-slogan{display:none}}@media(max-width:950px){.admin-wrap{padding-left:16px!important}.admin-head{margin:0 -16px 18px!important}.admin-head h1{font-size:34px!important}.hub-head-meta{justify-content:flex-start}.hub-kpis{grid-template-columns:1fr 1fr}}@media(max-width:650px){.hub-kpis{grid-template-columns:1fr}.admin-actions{grid-template-columns:1fr!important}.hub-head-meta{grid-column:auto;flex-wrap:wrap}.hub-chart{gap:8px}.hub-bar{max-width:32px}}
 `;document.head.appendChild(st);

 function ensureHeader(){const h=document.querySelector('.admin-head');if(!h||h.dataset.mockReady)return;h.dataset.mockReady='1';const actions=h.querySelector('.admin-actions');if(actions){const meta=document.createElement('div');meta.className='hub-head-meta';const d=new Date();meta.innerHTML=`<div class="hub-date">▣ ${d.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}</div><div class="hub-profile"><div class="hub-avatar">L</div><div><b>Larissa</b><small>Administrativo</small></div><span>⌄</span></div>`;actions.prepend(meta)}const s=document.createElement('div');s.className='hub-slogan';s.innerHTML='<span>Disciplina</span><span>gera resultado ♡</span>';h.appendChild(s)}

 async function enhanceSummary(){const pane=document.querySelector('[data-pane="resumo"]');if(!pane||pane.dataset.mockReady)return;pane.dataset.mockReady='loading';const [rr,ee]=await Promise.all([supabase.from('retiradas').select('*').order('created_at',{ascending:false}),supabase.from('entradas_estoque').select('*').order('created_at',{ascending:false})]);if(rr.error||ee.error){pane.dataset.mockReady='';return}const rows=rr.data||[],ents=ee.data||[];const stock={...BASE};ents.forEach(e=>{if(stock[e.tipo_caixa]!=null)stock[e.tipo_caixa]+=Number(e.total_caixas||0)});rows.forEach(r=>{if(stock[r.tipo_caixa]!=null)stock[r.tipo_caixa]-=Number(r.total_caixas||0)});const total=Object.values(stock).reduce((a,b)=>a+b,0);const td=todayKey(),mk=monthKey();const retirHoje=rows.filter(r=>String(r.created_at||'').slice(0,10)===td).reduce((a,r)=>a+Number(r.total_caixas||0),0);const entradasMes=ents.filter(e=>String(e.created_at||'').slice(0,7)===mk).reduce((a,e)=>a+Number(e.total_caixas||0),0);const mesRows=rows.filter(r=>String(r.created_at||'').slice(0,7)===mk),media=mesRows.length?mesRows.reduce((a,r)=>a+Number(r.total_caixas||0),0)/mesRows.length:0;
 const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);const k=d.toLocaleDateString('en-CA'),label=d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}),value=rows.filter(r=>String(r.created_at||'').slice(0,10)===k).reduce((a,r)=>a+Number(r.total_caixas||0),0);days.push({k,label,value})}const max=Math.max(1,...days.map(x=>x.value));
 const moves=[...rows.slice(0,12).map(r=>({date:r.created_at,type:'Retirada',box:r.tipo_caixa,qty:r.total_caixas,user:r.responsavel||'—',obs:'Retirada registrada'})),...ents.slice(0,12).map(e=>({date:e.created_at,type:'Entrada',box:e.tipo_caixa,qty:e.total_caixas,user:'Larissa',obs:e.observacao||'Entrada de estoque'}))].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,6);
 pane.innerHTML=`<div class="hub-summary"><div class="hub-kpis"><div class="hub-kpi"><div class="hub-kpi-icon">◇</div><div><span>Estoque total de caixas</span><strong>${br(total)}</strong><small class="up">↑ saldo atual</small></div></div><div class="hub-kpi"><div class="hub-kpi-icon">▣</div><div><span>Retiradas hoje</span><strong>${br(retirHoje)}</strong><small>caixas retiradas</small></div></div><div class="hub-kpi"><div class="hub-kpi-icon">🛒</div><div><span>Compras no mês</span><strong>${br(entradasMes)}</strong><small>unidades adicionadas</small></div></div><div class="hub-kpi"><div class="hub-kpi-icon">▥</div><div><span>Média de caixas por retirada</span><strong>${media.toLocaleString('pt-BR',{maximumFractionDigits:1})}</strong><small>mês atual</small></div></div></div><div class="hub-summary-grid"><div class="hub-panel"><div class="hub-panel-head"><h2>▥ Consumo de caixas (últimos 7 dias)</h2><span class="hub-range">Últimos 7 dias⌄</span></div><div class="hub-chart">${days.map(d=>`<div class="hub-bar-wrap"><div class="hub-bar-val">${d.value||''}</div><div class="hub-bar" style="height:${Math.max(2,d.value/max*88)}%"></div><div class="hub-day">${d.label}</div></div>`).join('')}</div></div><div class="hub-panel hub-moves"><div class="hub-panel-head"><h2>▣ Últimas movimentações</h2></div><table><thead><tr><th>DATA/HORA</th><th>TIPO</th><th>CAIXA</th><th>QUANTIDADE</th><th>USUÁRIO</th><th>OBSERVAÇÃO</th></tr></thead><tbody>${moves.map(m=>`<tr><td>${fmtDate(m.date)} ${fmtTime(m.date)}</td><td><span class="hub-tag ${m.type==='Entrada'?'in':'out'}">${m.type}</span></td><td>${esc(m.box)}</td><td>${br(m.qty)}</td><td>${esc(m.user)}</td><td>${esc(m.obs)}</td></tr>`).join('')||'<tr><td colspan="6">Nenhuma movimentação.</td></tr>'}</tbody></table><div class="hub-more">Ver todas as movimentações →</div></div></div></div>`;pane.dataset.mockReady='1'}

 const run=()=>{ensureHeader();enhanceSummary()};
 const ob=new MutationObserver(()=>{requestAnimationFrame(run)});ob.observe(document.body,{childList:true,subtree:true});addEventListener('DOMContentLoaded',run);setTimeout(run,150);setTimeout(run,700);
}
