import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const supabase=createClient("https://c--09586474-253e-4035-b48c-481591adc286-prod.lovable.cloud","sb_publishable_4zkSUbnHOH5kawdNM3d6lQ_xd5Do3bb");
const BASE={PP:1575,P:5550,M:1200},A=document.querySelector('#app'),path=location.pathname.toLowerCase();
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=d=>new Date(d).toLocaleString('pt-BR');
const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const mesAno=v=>{const [y,m]=String(v).slice(0,7).split('-');return y&&m?new Date(Number(y),Number(m)-1,1).toLocaleDateString('pt-BR',{month:'long',year:'numeric'}):'—'};
const badge=t=>`<span class="badge ${t==='PP'?'pp':t==='P'?'p':'m'}">${t}</span>`;

function home(){A.innerHTML=`<main class="wrap"><div class="home"><div class="brand">HUB</div><h1>RETIRADA DE CAIXAS</h1><p class="hint">Selecione o tipo de caixa para registrar a retirada. Cada fardo contém 25 caixas.</p><div class="types">${['PP','P','M'].map(t=>`<a class="type ${t==='PP'?'pp':t==='P'?'p':'m'}" href="/retirada/${t.toLowerCase()}"><span>📦</span><b>Caixa ${t}</b><small>25 caixas por fardo</small></a>`).join('')}</div></div></main>`}

function retirada(tipo){let f=1,c=tipo==='PP'?'pp':tipo==='P'?'p':'m';A.innerHTML=`<main class="wrap"><section class="panel"><header class="head ${c}"><div class="icon">📦</div><div class="eyebrow">RETIRADA DE CAIXAS</div><div class="title">CAIXA ${tipo}</div></header><div class="body"><p class="hint">Preencha os dados abaixo para registrar a retirada.</p><label class="label">RESPONSÁVEL</label><input id="nome" placeholder="Digite seu nome"><label class="label">QUANTIDADE DE FARDOS</label><div class="step"><button id="menos">−</button><div class="count" id="f">1</div><button id="mais">+</button></div><p class="center" id="txt">Você está retirando: 1 fardo</p><p class="center">Total: <span class="total ${c}" id="tot">25</span> caixas</p><div class="info"><b>1 FARDO = 25 CAIXAS</b></div><button class="primary ${c}" id="salvar">REGISTRAR RETIRADA</button></div></section></main>`;const upd=()=>{f=Math.max(1,Math.min(4,f));document.querySelector('#f').textContent=f;document.querySelector('#tot').textContent=f*25;document.querySelector('#txt').textContent=`Você está retirando: ${f} fardo${f>1?'s':''}`};document.querySelector('#menos').onclick=()=>{f--;upd()};document.querySelector('#mais').onclick=()=>{f++;upd()};document.querySelector('#salvar').onclick=async()=>{let nome=document.querySelector('#nome').value.trim();if(!nome)return alert('Digite o nome do responsável.');if(!confirm(`Confirmar retirada de ${f} fardo(s) da Caixa ${tipo}?`))return;let {error}=await supabase.from('retiradas').insert({tipo_caixa:tipo,fardos:f,total_caixas:f*25,responsavel:nome});if(error)return alert('Não foi possível registrar: '+error.message);alert('Retirada registrada com sucesso!');location.href='/';}}

function calc(rows,entradas){let o={PP:{usado:0,entrada:0},P:{usado:0,entrada:0},M:{usado:0,entrada:0}};rows.forEach(r=>o[r.tipo_caixa]&&(o[r.tipo_caixa].usado+=Number(r.total_caixas)||0));entradas.forEach(r=>o[r.tipo_caixa]&&(o[r.tipo_caixa].entrada+=Number(r.total_caixas)||0));for(let k of ['PP','P','M'])o[k].saldo=BASE[k]+o[k].entrada-o[k].usado;return o}

async function admin(){
  A.innerHTML=`<main class="admin-wrap"><section class="admin-shell"><header class="admin-head"><div><div class="admin-kicker">HUB • CONTROLE OPERACIONAL</div><h1>Painel Administrativo</h1><p>Acompanhe estoque, retiradas, entradas e valores de compras.</p></div><div class="admin-actions"><a class="ghost-btn" href="/">+ Nova retirada</a><a class="ghost-btn" href="/qrcodes">QR Codes</a></div></header><nav class="tabs"><button class="tab active" data-tab="resumo">Resumo</button><button class="tab" data-tab="retiradas">Retiradas</button><button class="tab" data-tab="entradas">Entrada de estoque</button><button class="tab" data-tab="compras">Controle de compras</button><button class="tab" data-tab="relatorios">Relatórios</button></nav><div id="loading" class="loading">Carregando dados...</div><div id="content" hidden></div></section></main>`;
  let [rr,ee,cc]=await Promise.all([
    supabase.from('retiradas').select('*').order('created_at',{ascending:false}),
    supabase.from('entradas_estoque').select('*').order('created_at',{ascending:false}),
    supabase.from('compras_controle').select('*').order('competencia',{ascending:false}).order('created_at',{ascending:false})
  ]);
  document.querySelector('#loading').remove();
  let C=document.querySelector('#content');C.hidden=false;
  if(rr.error||ee.error||cc.error){C.innerHTML=`<div class="errorbox">Erro ao carregar: ${esc((rr.error||ee.error||cc.error).message)}</div>`;return}
  let rows=rr.data||[],entradas=ee.data||[],compras=cc.data||[],active='resumo';

  const resumoCompras=()=>{
    const mapa={};
    compras.forEach(c=>{const k=String(c.competencia).slice(0,7);mapa[k]=(mapa[k]||0)+Number(c.valor||0)});
    return Object.entries(mapa).sort((a,b)=>b[0].localeCompare(a[0]));
  };

  const render=()=>{
    let t=calc(rows,entradas),total=['PP','P','M'].reduce((s,k)=>s+t[k].saldo,0),mensais=resumoCompras(),totalCompras=compras.reduce((s,c)=>s+Number(c.valor||0),0);
    C.innerHTML=`
      <section class="tabpane" data-pane="resumo" ${active==='resumo'?'':'hidden'}>
        <div class="cards">${['PP','P','M'].map(k=>`<div class="metric ${k==='PP'?'pp':k==='P'?'p':'m'}"><span>ESTOQUE ATUAL ${k}</span><strong>${t[k].saldo}</strong><small>Inicial ${BASE[k]} • +${t[k].entrada} entradas • -${t[k].usado} utilizadas</small></div>`).join('')}<div class="metric totalmetric"><span>ESTOQUE TOTAL ATUAL</span><strong>${total}</strong><small>Saldo disponível</small></div></div>
        <div class="section-card"><h2>Últimas retiradas</h2><div class="table-scroll"><table class="table"><thead><tr><th>Data/Hora</th><th>Responsável</th><th>Tipo</th><th>Fardos</th><th>Caixas</th></tr></thead><tbody>${rows.slice(0,8).map(r=>`<tr><td>${fmt(r.created_at)}</td><td><b>${esc(r.responsavel)}</b></td><td>${badge(r.tipo_caixa)}</td><td>${r.fardos}</td><td>${r.total_caixas}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nenhuma retirada.</td></tr>'}</tbody></table></div></div>
      </section>

      <section class="tabpane" data-pane="retiradas" ${active==='retiradas'?'':'hidden'}><div class="section-card"><h2>Retiradas</h2><div class="table-scroll"><table class="table"><thead><tr><th>Data/Hora</th><th>Responsável</th><th>Tipo</th><th>Fardos</th><th>Caixas</th><th>Ação</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${fmt(r.created_at)}</td><td>${esc(r.responsavel)}</td><td>${badge(r.tipo_caixa)}</td><td>${r.fardos}</td><td>${r.total_caixas}</td><td><button class="filter-btn" data-del-r="${r.id}">Excluir</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Nenhuma retirada.</td></tr>'}</tbody></table></div><br><button class="ghost-btn" id="limparTodos" style="color:#b91c1c">Limpar todos os registros</button></div></section>

      <section class="tabpane" data-pane="entradas" ${active==='entradas'?'':'hidden'}>
        <div class="section-card"><h2>Nova compra / Entrada de estoque</h2><div class="filters"><div><label>Tipo de caixa</label><select id="eTipo"><option>PP</option><option>P</option><option>M</option></select></div><div><label>Quantidade de fardos</label><input id="eFardos" type="number" min="1" value="1"></div><div><label>Observação</label><input id="eObs" placeholder="Ex.: Compra fornecedor"></div><button class="export-btn" id="salvarEntrada">REGISTRAR ENTRADA</button></div><p class="hint">Cada fardo adiciona 25 caixas ao estoque.</p></div>
        <div class="section-card"><h2>Histórico de entradas</h2><div class="table-scroll"><table class="table"><thead><tr><th>Data/Hora</th><th>Tipo</th><th>Fardos</th><th>Caixas</th><th>Observação</th><th>Ação</th></tr></thead><tbody>${entradas.map(e=>`<tr><td>${fmt(e.created_at)}</td><td>${badge(e.tipo_caixa)}</td><td>${e.fardos}</td><td><b>${e.total_caixas}</b></td><td>${esc(e.observacao||'—')}</td><td><button class="filter-btn" data-del-e="${e.id}">Excluir</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Nenhuma entrada registrada.</td></tr>'}</tbody></table></div></div>
      </section>

      <section class="tabpane" data-pane="compras" ${active==='compras'?'':'hidden'}>
        <div class="section-card"><h2>Controle mensal de compras</h2><p class="hint">Este controle é somente financeiro e não altera a quantidade de caixas em estoque.</p><div class="filters"><div><label>Mês da compra</label><input id="cMes" type="month" value="${new Date().toISOString().slice(0,7)}"></div><div><label>Valor da compra</label><input id="cValor" type="number" min="0" step="0.01" placeholder="0,00"></div><div><label>Observação</label><input id="cObs" placeholder="Ex.: NF, fornecedor ou referência"></div><button class="export-btn" id="salvarCompra">REGISTRAR VALOR</button></div></div>
        <div class="cards report-cards"><div class="metric neutral"><span>TOTAL REGISTRADO</span><strong>${brl(totalCompras)}</strong><small>Todos os meses</small></div><div class="metric neutral"><span>MESES COM COMPRA</span><strong>${mensais.length}</strong><small>Competências registradas</small></div></div>
        <div class="section-card"><h2>Resumo por mês</h2><div class="table-scroll"><table class="table"><thead><tr><th>Mês</th><th>Valor total</th></tr></thead><tbody>${mensais.map(([m,v])=>`<tr><td><b>${mesAno(m)}</b></td><td><b>${brl(v)}</b></td></tr>`).join('')||'<tr><td colspan="2" class="empty">Nenhum valor de compra registrado.</td></tr>'}</tbody></table></div></div>
        <div class="section-card"><h2>Histórico de valores</h2><div class="table-scroll"><table class="table"><thead><tr><th>Mês</th><th>Valor</th><th>Observação</th><th>Registrado em</th><th>Ação</th></tr></thead><tbody>${compras.map(c=>`<tr><td>${mesAno(c.competencia)}</td><td><b>${brl(c.valor)}</b></td><td>${esc(c.observacao||'—')}</td><td>${fmt(c.created_at)}</td><td><button class="filter-btn" data-del-c="${c.id}">Excluir</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nenhum valor registrado.</td></tr>'}</tbody></table></div></div>
      </section>

      <section class="tabpane" data-pane="relatorios" ${active==='relatorios'?'':'hidden'}><div class="section-card"><h2>Resumo do estoque</h2><div class="table-scroll"><table class="table"><thead><tr><th>Tipo</th><th>Estoque inicial</th><th>Entradas</th><th>Utilizadas</th><th>Saldo atual</th></tr></thead><tbody>${['PP','P','M'].map(k=>`<tr><td>${badge(k)}</td><td>${BASE[k]}</td><td>+${t[k].entrada}</td><td>-${t[k].usado}</td><td><b>${t[k].saldo}</b></td></tr>`).join('')}</tbody></table></div></div></section>`;
    bind();
  };

  const bind=()=>{
    document.querySelectorAll('.tab').forEach(b=>{b.classList.toggle('active',b.dataset.tab===active);b.onclick=()=>{active=b.dataset.tab;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===active));document.querySelectorAll('.tabpane').forEach(p=>p.hidden=p.dataset.pane!==active)}});
    let se=document.querySelector('#salvarEntrada');if(se)se.onclick=async()=>{let tipo=document.querySelector('#eTipo').value,f=Number(document.querySelector('#eFardos').value),obs=document.querySelector('#eObs').value.trim();if(!Number.isInteger(f)||f<1)return alert('Informe uma quantidade válida de fardos.');if(!confirm(`Adicionar ${f} fardo(s) = ${f*25} caixas ${tipo} ao estoque?`))return;let {data,error}=await supabase.from('entradas_estoque').insert({tipo_caixa:tipo,fardos:f,total_caixas:f*25,observacao:obs||null}).select().single();if(error)return alert('Não foi possível registrar: '+error.message);entradas.unshift(data);render();alert('Entrada registrada e estoque atualizado.');};
    let sc=document.querySelector('#salvarCompra');if(sc)sc.onclick=async()=>{let mes=document.querySelector('#cMes').value,valor=Number(document.querySelector('#cValor').value),obs=document.querySelector('#cObs').value.trim();if(!mes)return alert('Selecione o mês da compra.');if(!Number.isFinite(valor)||valor<0)return alert('Informe um valor válido.');let competencia=mes+'-01';if(!confirm(`Registrar ${brl(valor)} para ${mesAno(mes)}?\n\nEste valor não altera o estoque.`))return;let {data,error}=await supabase.from('compras_controle').insert({competencia,valor,observacao:obs||null}).select().single();if(error)return alert('Não foi possível registrar: '+error.message);compras.push(data);compras.sort((a,b)=>String(b.competencia).localeCompare(String(a.competencia))||String(b.created_at).localeCompare(String(a.created_at)));render();alert('Valor de compra registrado. O estoque não foi alterado.');};
    C.onclick=async e=>{let br=e.target.closest('[data-del-r]'),be=e.target.closest('[data-del-e]'),bc=e.target.closest('[data-del-c]');if(br){if(!confirm('Excluir esta retirada? As caixas voltarão ao estoque.'))return;let {error}=await supabase.from('retiradas').delete().eq('id',br.dataset.delR);if(error)return alert(error.message);rows=rows.filter(x=>String(x.id)!==br.dataset.delR);render()}if(be){if(!confirm('Excluir esta entrada? O saldo será reduzido.'))return;let {error}=await supabase.from('entradas_estoque').delete().eq('id',be.dataset.delE);if(error)return alert(error.message);entradas=entradas.filter(x=>String(x.id)!==be.dataset.delE);render()}if(bc){if(!confirm('Excluir este valor de compra? Isso não altera o estoque.'))return;let {error}=await supabase.from('compras_controle').delete().eq('id',bc.dataset.delC);if(error)return alert(error.message);compras=compras.filter(x=>String(x.id)!==bc.dataset.delC);render()}if(e.target.id==='limparTodos'){if(!rows.length)return alert('Não há retiradas para apagar.');if(prompt('Digite LIMPAR para apagar todas as retiradas:')!=='LIMPAR')return;let {error}=await supabase.from('retiradas').delete().not('created_at','is',null);if(error)return alert(error.message);rows=[];render();}};
  };
  render();
}

function qrs(){let base=location.origin;A.innerHTML=`<main class="qr-page"><section class="qr-shell"><header class="qr-head"><div><h1>QR CODES DAS CAIXAS</h1></div></header><div class="qrgrid">${['PP','P','M'].map(t=>{let u=base+'/retirada/'+t.toLowerCase();return `<article class="qrcard"><div class="qr-label">CAIXA ${t}</div><img src="https://quickchart.io/qr?size=300&margin=2&text=${encodeURIComponent(u)}"><strong>25 CAIXAS POR FARDO</strong></article>`}).join('')}</div></section></main>`}
if(path==='/admin')admin();else if(path==='/qrcodes')qrs();else if(path.startsWith('/retirada/')){let t=path.split('/').pop().toUpperCase();['PP','P','M'].includes(t)?retirada(t):home()}else home();