import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const supabase=createClient("https://c--09586474-253e-4035-b48c-481591adc286-prod.lovable.cloud","sb_publishable_4zkSUbnHOH5kawdNM3d6lQ_xd5Do3bb");
const TYPES=['PP','P','M'], BASE={PP:1575,P:5550,M:1200}, PREFIX='__CAIXA_CUSTO__';
const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), esc=s=>String(s??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=s=>Number(String(s||'').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''))||0;
const month=k=>{const [y,m]=String(k||'').slice(0,7).split('-');return y&&m?new Date(+y,+m-1,1).toLocaleDateString('pt-BR',{month:'long',year:'numeric'}):'—'};
function meta(r){const o=String(r.observacao||'');if(!o.startsWith(PREFIX))return null;try{return JSON.parse(o.slice(PREFIX.length))}catch{return null}}
function encoded(tipo,caixas,nota){return PREFIX+JSON.stringify({tipo,caixas:Number(caixas)||0,nota:nota||''})}
function stock(rows,entries){const s={...BASE};entries.forEach(x=>s[x.tipo_caixa]!=null&&(s[x.tipo_caixa]+=Number(x.total_caixas||0)));rows.forEach(x=>s[x.tipo_caixa]!=null&&(s[x.tipo_caixa]-=Number(x.total_caixas||0)));return s}
async function render(pane){
 pane.innerHTML='<div class="section-card"><h2>Custos das caixas</h2><p class="hint">Carregando informações financeiras...</p></div>';
 const [cr,rr,er]=await Promise.all([supabase.from('compras_controle').select('*').order('competencia',{ascending:false}).order('created_at',{ascending:false}),supabase.from('retiradas').select('tipo_caixa,total_caixas'),supabase.from('entradas_estoque').select('tipo_caixa,total_caixas')]);
 if(cr.error||rr.error||er.error){pane.innerHTML=`<div class="section-card"><h2>Custos das caixas</h2><div class="errorbox">Não foi possível carregar os custos: ${esc((cr.error||rr.error||er.error).message)}</div></div>`;return}
 const compras=cr.data||[], s=stock(rr.data||[],er.data||[]), usable=compras.map(c=>({c,m:meta(c)})).filter(x=>x.m&&TYPES.includes(x.m.tipo)&&Number(x.m.caixas)>0&&Number(x.c.valor)>0), per={};
 TYPES.forEach(t=>{const a=usable.filter(x=>x.m.tipo===t),v=a.reduce((z,x)=>z+Number(x.c.valor||0),0),q=a.reduce((z,x)=>z+Number(x.m.caixas||0),0);per[t]={v,q,avg:q?v/q:0}});
 const total=usable.reduce((z,x)=>z+Number(x.c.valor||0),0), saldo=TYPES.reduce((z,t)=>z+Math.max(0,s[t]),0), valorSaldo=TYPES.reduce((z,t)=>z+Math.max(0,s[t])*per[t].avg,0), byMonth={};
 compras.forEach(c=>{const k=String(c.competencia||'').slice(0,7);if(k)byMonth[k]=(byMonth[k]||0)+Number(c.valor||0)});
 pane.innerHTML=`<div class="section-card cost-hero"><div><div class="admin-kicker">HUB • FINANCEIRO</div><h2>Controle de custos das caixas</h2><p class="hint">Compras históricas entram no financeiro e <b>não alteram o estoque</b>.</p></div><span class="cost-safe">✓ Estoque protegido</span></div>
 <div class="cards report-cards"><div class="metric neutral"><span>COMPRAS CADASTRADAS</span><strong>${brl(total)}</strong><small>Histórico financeiro</small></div><div class="metric neutral"><span>ESTOQUE ATUAL</span><strong>${saldo}</strong><small>Caixas disponíveis</small></div><div class="metric neutral"><span>VALOR ESTIMADO DO ESTOQUE</span><strong>${brl(valorSaldo)}</strong><small>Pelo custo médio cadastrado</small></div></div>
 <div class="section-card"><h2>Registrar compra passada</h2><div class="filters"><div><label>Mês da compra</label><input id="cxMes" type="month"></div><div><label>Tipo de caixa</label><select id="cxTipo">${TYPES.map(t=>`<option>${t}</option>`).join('')}</select></div><div><label>Unidade de compra</label><select id="cxUnidade"><option value="unidade">Unidade</option></select></div><div><label>Quantidade comprada</label><input id="cxQtd" type="number" min="1" value="1"></div><div><label>Valor total</label><input id="cxValor" inputmode="decimal" placeholder="Ex.: 1.250,00"></div><div><label>Fornecedor</label><input id="cxFornecedor" placeholder="Opcional"></div><div><label>NF</label><input id="cxNF" placeholder="Opcional"></div><div><label>Observação</label><input id="cxObs" placeholder="Opcional"></div><button class="export-btn" id="cxSalvar">REGISTRAR COMPRA</button></div><p class="hint">A quantidade é registrada diretamente em unidades de caixas.</p></div>
 <div class="section-card"><h2>Custo médio e valor do saldo</h2><div class="table-scroll"><table class="table"><thead><tr><th>Tipo</th><th>Unidades compradas</th><th>Valor informado</th><th>Custo médio/unidade</th><th>Saldo atual</th><th>Valor estimado saldo</th></tr></thead><tbody>${TYPES.map(t=>`<tr><td><b>${t}</b></td><td>${per[t].q||'—'}</td><td>${per[t].v?brl(per[t].v):'—'}</td><td>${per[t].avg?`<b>${brl(per[t].avg)}</b>`:'—'}</td><td>${s[t]}</td><td>${per[t].avg?`<b>${brl(Math.max(0,s[t])*per[t].avg)}</b>`:'—'}</td></tr>`).join('')}</tbody></table></div></div>
 <div class="section-card"><h2>Compras por mês</h2><div class="table-scroll"><table class="table"><thead><tr><th>Mês</th><th>Valor total</th></tr></thead><tbody>${Object.entries(byMonth).sort((a,b)=>b[0].localeCompare(a[0])).map(([m,v])=>`<tr><td><b>${month(m)}</b></td><td><b>${brl(v)}</b></td></tr>`).join('')||'<tr><td colspan="2" class="empty">Nenhuma compra cadastrada.</td></tr>'}</tbody></table></div></div>
 <div class="section-card"><h2>Histórico de compras</h2><div class="table-scroll"><table class="table"><thead><tr><th>Mês</th><th>Tipo</th><th>Unidades</th><th>Valor</th><th>Custo/unidade</th><th>Fornecedor</th><th>NF</th><th>Observação</th><th>Ação</th></tr></thead><tbody>${compras.map(c=>{const m=meta(c),q=m?.caixas||0;return `<tr><td>${month(c.competencia)}</td><td>${m?.tipo||'—'}</td><td>${q||'—'}</td><td><b>${brl(c.valor)}</b></td><td>${q?brl(Number(c.valor||0)/q):'—'}</td><td>${esc(c.fornecedor||'—')}</td><td>${esc(c.nf||'—')}</td><td>${esc(m?.nota||'—')}</td><td><button class="filter-btn cxDel" data-id="${c.id}">Excluir</button></td></tr>`}).join('')||'<tr><td colspan="9" class="empty">Nenhuma compra cadastrada.</td></tr>'}</tbody></table></div></div>`;
 const mes=pane.querySelector('#cxMes');if(mes)mes.value=new Date().toISOString().slice(0,7);
 pane.querySelector('#cxSalvar').onclick=async()=>{const competencia=mes.value,tipo=pane.querySelector('#cxTipo').value,q=Math.max(1,Number(pane.querySelector('#cxQtd').value||1)),valor=money(pane.querySelector('#cxValor').value);if(!competencia)return alert('Informe o mês da compra.');if(!valor)return alert('Informe o valor total da compra.');const fornecedor=pane.querySelector('#cxFornecedor').value.trim(),nf=pane.querySelector('#cxNF').value.trim(),nota=pane.querySelector('#cxObs').value.trim();const {error}=await supabase.from('compras_controle').insert({competencia:competencia+'-01',valor,fornecedor:fornecedor||null,nf:nf||null,observacao:encoded(tipo,q,nota)});if(error)return alert('Não foi possível salvar: '+error.message);alert('Compra registrada sem alterar o estoque.');render(pane)};
 pane.querySelectorAll('.cxDel').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir esta compra?'))return;const {error}=await supabase.from('compras_controle').delete().eq('id',b.dataset.id);if(error)return alert(error.message);render(pane)});
}
function mount(){if(!location.pathname.toLowerCase().startsWith('/admin'))return;const tabs=document.querySelector('.tabs'),shell=document.querySelector('.admin-shell');if(!tabs||!shell)return setTimeout(mount,150);let tab=document.querySelector('#custosCaixasTab');if(!tab){tab=document.createElement('button');tab.className='tab';tab.id='custosCaixasTab';tab.textContent='Custos das caixas';tabs.appendChild(tab)}let pane=document.querySelector('#custosCaixasStandalone');if(!pane){pane=document.createElement('section');pane.id='custosCaixasStandalone';pane.hidden=true;shell.appendChild(pane)}tab.onclick=async e=>{e.preventDefault();e.stopPropagation();document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');const content=document.querySelector('#content');if(content)content.hidden=true;pane.hidden=false;await render(pane)};tabs.querySelectorAll('.tab:not(#custosCaixasTab)').forEach(b=>b.addEventListener('click',()=>{pane.hidden=true;const content=document.querySelector('#content');if(content)content.hidden=false}));}
addEventListener('DOMContentLoaded',mount);setTimeout(mount,100);setTimeout(mount,700);
