// Visual aprovado: replica estruturalmente o mockup no painel real.
if(location.pathname.toLowerCase().startsWith('/admin')){
const css=document.createElement('style');css.textContent=`
:root{--teal:#006b78;--teal-dark:#004f5d;--navy:#0b2349;--page:#f4f8fa;--border:#d9e6e9}
*{box-sizing:border-box}body{background:var(--page)!important;color:var(--navy)!important}
.admin-wrap{padding:0 14px 28px 220px!important;background:var(--page)!important}.admin-shell{width:100%!important;max-width:none!important}
.tabs{width:205px!important;background:linear-gradient(180deg,#006979 0%,#004f5d 100%)!important;border:0!important;padding:18px 10px!important;box-shadow:none!important}
.tabs:before{content:'◇\A Caixas e Fita\A Gomada HUB'!important;white-space:pre!important;color:#fff!important;font-size:20px!important;line-height:1.08!important;font-weight:900!important;padding:0 10px 12px!important}
.tabs:after{content:'Controle de Estoque Inteligente'!important;color:#bde1e5!important;margin:0 10px 18px!important;padding:0 0 14px!important;border-bottom:1px solid #267b87!important;font-size:8px!important}
.tab{color:#f4fbfc!important;font-size:12px!important;font-weight:650!important;padding:11px 8px 11px 40px!important;margin:1px 0!important;border-radius:8px!important}.tab:hover,.tab.active{background:#087987!important;color:#fff!important}
.admin-head{height:52px!important;min-height:52px!important;margin:0 -14px 12px!important;padding:8px 18px!important;background:linear-gradient(90deg,#0a8390,#006270)!important;border:0!important;border-radius:0!important;box-shadow:none!important}
.admin-head>div:first-child{display:flex;flex-direction:column;justify-content:center}.admin-head h1{font-size:15px!important;color:#fff!important;margin:0!important}.admin-head p{font-size:9px!important;color:#ddf2f4!important;margin:1px 0 0!important}.admin-kicker{display:none!important}.admin-actions{gap:7px!important}.ghost-btn{font-size:10px!important;padding:7px 10px!important;border-radius:8px!important;background:#fff!important;color:#075b67!important;border:0!important}
[data-pane="resumo"]>.cards{display:none!important}
.forecast-wrap{margin:0!important}.forecast-head{border:0!important;background:transparent!important;padding:3px 5px 9px!important}.forecast-head h2{font-size:24px!important;color:#0b2349!important;line-height:1!important}.forecast-head p{font-size:11px!important;color:#45667a!important;margin-top:5px!important}
.forecast-summary{grid-template-columns:repeat(4,1fr)!important;gap:9px!important;margin:0 0 10px!important}.forecast-summary>div{min-height:76px!important;padding:13px 12px 10px 58px!important;border:1px solid var(--border)!important;border-radius:9px!important;box-shadow:none!important;position:relative!important;background:#fff!important}.forecast-summary>div:before{position:absolute;left:13px;top:13px;width:34px;height:34px;display:grid;place-items:center;border-radius:8px;background:#e3f6f8;color:#087783;font-size:20px!important}.forecast-summary>div:nth-child(1):before{content:'▣'}.forecast-summary>div:nth-child(2):before{content:'⚠';background:#fff0ef;color:#e4574e}.forecast-summary>div:nth-child(3):before{content:'▰'}.forecast-summary>div:nth-child(4):before{content:'▥'}.forecast-summary span{font-size:9px!important;color:#173653!important}.forecast-summary b{font-size:23px!important;color:#0b2349!important;margin-top:3px!important}
.forecast-grid{grid-template-columns:repeat(3,1fr)!important;gap:9px!important;margin-bottom:9px!important}.forecast-card{padding:13px!important;border-radius:9px!important;border:1px solid var(--border)!important;box-shadow:none!important;background:#fff!important}.forecast-card h3{font-size:15px!important;color:#0b2349!important;margin:0 0 9px!important}.forecast-kpis{gap:6px!important}.forecast-kpi{padding:8px!important;border-radius:7px!important;background:#f3f9fa!important;border:1px solid #dcebed!important}.forecast-kpi span{font-size:8px!important;color:#5a7680!important}.forecast-kpi b{font-size:12px!important;color:#102b4c!important}.forecast-priority{font-size:8px!important;padding:4px 8px!important}
.charts{grid-template-columns:repeat(3,1fr)!important;gap:9px!important;margin-top:0!important}.chart-card{height:215px!important;padding:11px!important;border:1px solid var(--border)!important;border-radius:9px!important;box-shadow:none!important;background:#fff!important}.chart-card h3{font-size:11px!important;color:#0b2349!important}.chart-card small{font-size:9px!important}.bars,.trendbox{height:160px!important}
.plan-card{padding:11px!important;border-radius:9px!important;border:1px solid var(--border)!important;box-shadow:none!important;margin-top:9px!important;background:#fff!important}.plan-card h3{font-size:12px!important;color:#0b2349!important}.plan-card p{font-size:9px!important}.plan-table{font-size:9px!important}.plan-table th{font-size:7px!important;background:#eef4f6!important}.plan-table th,.plan-table td{padding:6px!important}
.tip-card{margin-top:9px!important;padding:10px 12px!important;border-radius:9px!important;background:#eef8f9!important;font-size:10px!important}
@media(max-width:1050px){.forecast-summary{grid-template-columns:1fr 1fr!important}.forecast-grid,.charts{grid-template-columns:1fr!important}.chart-card{height:auto!important}}
`;document.head.appendChild(css);
function apply(){const pane=document.querySelector('[data-pane="resumo"]');if(!pane)return;
const head=document.querySelector('.admin-head');if(head){const h=head.querySelector('h1');if(h)h.textContent='Olá, Administrador!';const p=head.querySelector('p');if(p)p.textContent='Aqui está o resumo do seu estoque e das próximas ações.'}
const fw=pane.querySelector('.forecast-wrap');if(fw){const h=fw.querySelector('.forecast-head h2');if(h)h.textContent='Resumo Geral';const p=fw.querySelector('.forecast-head p');if(p)p.textContent='Visão completa do seu estoque e das próximas ações';}
const tabs=document.querySelector('.tabs');if(tabs){const labels={resumo:'Resumo',entradas:'Entradas',retiradas:'Retiradas',compras:'Compras',inventario:'Inventário',consumo:'Previsão e Planejamento',relatorios:'Relatórios',fita:'Fita Gomada'};tabs.querySelectorAll('.tab').forEach(b=>{if(labels[b.dataset.tab])b.textContent=labels[b.dataset.tab]})}
}
new MutationObserver(apply).observe(document.getElementById('app'),{subtree:true,childList:true});[0,200,600,1200].forEach(t=>setTimeout(apply,t));
}