// Dashboard administrativo v2 — interface única, sem sobreposições antigas
if(location.pathname.toLowerCase().startsWith('/admin')){
const style=document.createElement('style');style.textContent=`
@media(min-width:951px){.admin-wrap{padding-left:225px!important;padding-top:0!important}.admin-shell{max-width:none!important;width:100%!important}.tabs{width:210px!important;background:linear-gradient(180deg,#006979,#004d5b)!important;padding:20px 10px!important}.tabs:before{content:'◇  HUB'!important;color:#fff!important;font-size:25px!important}.tabs:after{content:'CAIXAS E FITA GOMADA\A Controle de Estoque Inteligente'!important;white-space:pre!important;color:#c8e8eb!important;font-size:9px!important;line-height:1.5!important;margin:5px 8px 22px!important}.tab{color:#f4fbfc!important;padding:12px 10px 12px 42px!important;border-radius:8px!important;font-size:12px!important}.tab.active,.tab:hover{background:#087986!important}.tab:before{color:#fff!important}}
body{background:#f4f8fa!important}.admin-head{min-height:52px!important;background:linear-gradient(90deg,#0a8491,#006371)!important;border:0!important;border-radius:0!important;margin-bottom:12px!important;padding:9px 18px!important}.admin-head h1{font-size:16px!important;color:#fff!important;margin:0!important}.admin-head p{font-size:10px!important;color:#dff2f4!important;margin:2px 0!important}.admin-kicker{display:none!important}.ghost-btn{background:#fff!important;color:#075d69!important;border:0!important;border-radius:8px!important;font-size:10px!important;padding:8px 11px!important}
.v2{color:#0c2749}.v2-title{display:flex;justify-content:space-between;align-items:flex-end;margin:3px 2px 12px}.v2-title h2{font-size:25px;margin:0}.v2-title p{font-size:11px;color:#557080;margin:3px 0 0}.v2-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:10px}.v2-kpi,.v2-panel,.v2-item,.v2-chart{background:#fff;border:1px solid #dbe7ea;border-radius:10px;box-shadow:0 2px 8px #24434d08}.v2-kpi{padding:14px 13px 12px 58px;min-height:82px;position:relative}.v2-kpi i{position:absolute;left:13px;top:15px;width:34px;height:34px;border-radius:8px;background:#e2f5f7;display:grid;place-items:center;font-style:normal;font-size:19px;color:#087886}.v2-kpi.warn i{background:#fff0ef;color:#df5149}.v2-kpi span{display:block;font-size:10px;color:#24445d}.v2-kpi b{font-size:24px}.v2-kpi small{display:block;color:#627b8a;font-size:9px}
.v2-tabs{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;background:#fff;padding:6px;border:1px solid #dbe7ea;border-radius:10px;margin-bottom:8px}.v2-tab{border:0;background:#edf4f6;padding:10px;border-radius:7px;font-weight:800;color:#16455c}.v2-tab.active{background:linear-gradient(90deg,#087d89,#006773);color:#fff}
.v2-panel{padding:13px;margin-bottom:9px}.v2-itemhead{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.v2-itemhead h3{font-size:20px;margin:0}.v2-itemhead small{color:#617a88}.v2-metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}.v2-item{padding:11px}.v2-item span{display:block;font-size:9px;color:#56717e}.v2-item b{font-size:18px}.v2-item small{display:block;font-size:9px;color:#667e8b;margin-top:2px}.v2-status{background:#fff0d5!important}.v2-status b{color:#d26a00}
.v2-charts{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-bottom:9px}.v2-chart{padding:12px;height:220px}.v2-chart h4{margin:0;font-size:12px}.v2-chart p{margin:2px 0 8px;font-size:9px;color:#637b87}.v2-bars{height:160px;display:flex;align-items:end;gap:12px;border-bottom:1px solid #cddde1;padding:8px}.v2-bar{flex:1;text-align:center;font-size:8px;color:#59737f}.v2-bar div{display:flex;align-items:end;justify-content:center;gap:3px;height:125px}.v2-bar i{display:block;width:18px;background:#078391;border-radius:3px 3px 0 0}.v2-bar em{display:block;width:18px;background:#cbdadd;border-radius:3px 3px 0 0}.v2-plan{background:#fff;border:1px solid #dbe7ea;border-radius:10px;padding:12px;overflow:auto}.v2-plan h3{margin:0;font-size:13px}.v2-plan p{font-size:9px;color:#647d88;margin:2px 0 8px}.v2-plan table{width:100%;border-collapse:collapse;font-size:9px}.v2-plan th{background:#eef4f6;font-size:8px}.v2-plan td,.v2-plan th{padding:7px;border-bottom:1px solid #e2ebed;text-align:left}.v2-pill{display:inline-block;border-radius:999px;padding:4px 10px;background:#e4f4e9;color:#27703f;font-weight:800}.v2-pill.att{background:#fff0d5;color:#a96400}.v2-tip{margin-top:9px;padding:11px;background:#edf8f9;border:1px solid #d4e9eb;border-radius:9px;font-size:10px}
@media(max-width:1100px){.v2-summary,.v2-metrics{grid-template-columns:repeat(2,1fr)}.v2-charts{grid-template-columns:1fr}}
`;document.head.appendChild(style);
const BASE={PP:1575,P:5550,M:1200},fmt=n=>Number(n||0).toLocaleString('pt-BR'),date=d=>d?d.toLocaleDateString('pt-BR'):'—';
async function dashboard(){const pane=document.querySelector('[data-pane="resumo"]');if(!pane||pane.dataset.v2)return;pane.dataset.v2='1';
try{const H={apikey:'sb_publishable_4zkSUbnHOH5kawdNM3d6lQ_xd5Do3bb'},U='https://c--09586474-253e-4035-b48c-481591adc286-prod.lovable.cloud/rest/v1/';
const req=q=>fetch(U+q,{headers:H}).then(x=>x.ok?x.json():Promise.reject(new Error('dados')));
const [r,e,i]=await Promise.all([req('retiradas?select=*'),req('entradas_estoque?select=*'),req('inventarios?select=*&order=data_inventario.desc')]);
const now=new Date(),d30=new Date(now-30*864e5),d7=new Date(now-7*864e5),types=['PP','P','M'],stock={...BASE};
types.forEach(t=>{stock[t]+=e.filter(x=>x.tipo_caixa===t).reduce((s,x)=>s+(+x.total_caixas||0),0)-r.filter(x=>x.tipo_caixa===t).reduce((s,x)=>s+(+x.total_caixas||0),0)});
if(i[0]){const inv=i[0],id=new Date(inv.data_inventario+'T23:59:59'),map={PP:'pp_contado',P:'p_contado',M:'m_contado'};types.forEach(t=>{stock[t]=(+inv[map[t]]||0)+e.filter(x=>x.tipo_caixa===t&&new Date(x.created_at)>id).reduce((s,x)=>s+(+x.total_caixas||0),0)-r.filter(x=>x.tipo_caixa===t&&new Date(x.created_at)>id).reduce((s,x)=>s+(+x.total_caixas||0),0)})}
const data={};types.forEach(t=>{const a=r.filter(x=>x.tipo_caixa===t),c30=a.filter(x=>new Date(x.created_at)>=d30).reduce((s,x)=>s+(+x.total_caixas||0),0),c7=a.filter(x=>new Date(x.created_at)>=d7).reduce((s,x)=>s+(+x.total_caixas||0),0),avg=c30/30,a7=c7/7,min=Math.ceil(avg*14),cov=avg?Math.floor(stock[t]/avg):999,trend=avg?Math.round((a7/avg-1)*100):0,qty=Math.max(0,Math.ceil(avg*44-stock[t])),rupt=avg?new Date(now.getTime()+cov*864e5):null,buy=avg?new Date(now.getTime()+Math.max(0,cov-14)*864e5):null;data[t]={avg,min,cov,trend,qty,rupt,buy}});
const total=types.reduce((s,t)=>s+stock[t],0),alerts=types.filter(t=>data[t].cov<=30).length,buys=types.filter(t=>data[t].qty>0).length,avg=types.reduce((s,t)=>s+data[t].avg,0);
pane.innerHTML=`<div class="v2"><div class="v2-title"><div><h2>Resumo Geral</h2><p>Visão completa do seu estoque e das próximas ações</p></div></div><div class="v2-summary">
<div class="v2-kpi"><i>▣</i><span>Estoque Total</span><b>${fmt(total)}</b><small>unidades</small></div><div class="v2-kpi warn"><i>⚠</i><span>Itens em Alerta</span><b>${alerts}</b><small>de 4 itens</small></div><div class="v2-kpi"><i>▰</i><span>Próximas Compras</span><b>${buys}</b><small>nos próximos 30 dias</small></div><div class="v2-kpi"><i>▥</i><span>Consumo Médio Diário</span><b>${avg.toLocaleString('pt-BR',{maximumFractionDigits:1})}</b><small>unidades/dia</small></div></div>
<div class="v2-tabs"><button class="v2-tab active">▣ Caixa PP</button><button class="v2-tab">▣ Caixa P</button><button class="v2-tab">▣ Caixa M</button><button class="v2-tab">◉ Fita Gomada</button></div><div id="v2detail"></div>
<div class="v2-charts"><div class="v2-chart"><h4>Estoque Atual x Estoque Mínimo</h4><p>Comparativo por item</p><div class="v2-bars">${types.map(t=>{const mx=Math.max(...types.map(x=>stock[x]),1);return `<div class="v2-bar"><div><i style="height:${Math.max(5,stock[t]/mx*120)}px"></i><em style="height:${Math.max(5,data[t].min/mx*120)}px"></em></div>${t}</div>`}).join('')}</div></div><div class="v2-chart"><h4>Consumo e Tendência</h4><p>Média diária dos últimos 30 dias</p><div class="v2-bars">${types.map(t=>`<div class="v2-bar"><div><i style="height:${Math.max(8,data[t].avg/Math.max(...types.map(x=>data[x].avg),1)*120)}px"></i></div>${t}<br>${data[t].avg.toFixed(1)}/dia</div>`).join('')}</div></div><div class="v2-chart"><h4>Projeção de Estoque — Caixa PP</h4><p>Com base no consumo médio atual</p><div style="padding:25px 10px;font-size:12px;line-height:2.2"><b>Hoje:</b> ${fmt(stock.PP)} caixas<br><b>30 dias:</b> ${fmt(Math.max(0,stock.PP-data.PP.avg*30))}<br><b>60 dias:</b> ${fmt(Math.max(0,stock.PP-data.PP.avg*60))}<br><b>90 dias:</b> ${fmt(Math.max(0,stock.PP-data.PP.avg*90))}</div></div></div>
<div class="v2-plan"><h3>Previsão e Planejamento - Todos os Itens</h3><p>Recomendações automáticas com base no seu consumo</p><table><thead><tr><th>Item</th><th>Estoque Atual</th><th>Estoque Mínimo</th><th>Cobertura</th><th>Consumo Médio</th><th>Tendência 7d</th><th>Previsão Ruptura</th><th>Data Ideal Compra</th><th>Qtd. Sugerida</th><th>Prioridade</th></tr></thead><tbody>${types.map(t=>`<tr><td><b>▣ Caixa ${t}</b></td><td><b>${fmt(stock[t])}</b></td><td>${fmt(data[t].min)}</td><td>${data[t].cov===999?'—':data[t].cov+' dias'}</td><td>${data[t].avg.toFixed(1)}/dia</td><td>${data[t].trend>=0?'+':''}${data[t].trend}%</td><td>${date(data[t].rupt)}</td><td>${date(data[t].buy)}</td><td>${fmt(data[t].qty)}</td><td><span class="v2-pill ${data[t].cov<=30?'att':''}">${data[t].cov<=14?'Comprar':data[t].cov<=30?'Atenção':'Normal'}</span></td></tr>`).join('')}<tr><td><b>◉ Fita Gomada</b></td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td><span class="v2-pill">Consultar</span></td></tr></tbody></table></div><div class="v2-tip">💡 <b>Dica:</b> compre antes da data recomendada para evitar ruptura e manter suas operações sem interrupções.</div></div>`;
function detail(t){const d=data[t];document.querySelector('#v2detail').innerHTML=`<div class="v2-panel"><div class="v2-itemhead"><div><h3>▣ Caixa ${t}</h3><small>Resumo e previsões</small></div><small>Período de análise • Últimos 30 dias</small></div><div class="v2-metrics"><div class="v2-item"><span>Estoque Atual</span><b>${fmt(stock[t])}</b><small>unidades</small></div><div class="v2-item"><span>Estoque Mínimo</span><b>${fmt(d.min)}</b><small>unidades</small></div><div class="v2-item"><span>Cobertura de Estoque</span><b>${d.cov===999?'—':d.cov}</b><small>dias</small></div><div class="v2-item"><span>Consumo Médio (30 dias)</span><b>${d.avg.toFixed(1)}</b><small>unidades/dia</small></div><div class="v2-item"><span>Tendência (7 dias)</span><b>${d.trend>=0?'+':''}${d.trend}%</b><small>vs. média de 30 dias</small></div><div class="v2-item"><span>Previsão de Ruptura</span><b>${date(d.rupt)}</b><small>estimativa</small></div><div class="v2-item"><span>Data Ideal para Comprar</span><b>${date(d.buy)}</b><small>estoque de segurança</small></div><div class="v2-item"><span>Quantidade Sugerida</span><b>${fmt(d.qty)}</b><small>unidades</small></div><div class="v2-item v2-status"><span>Prioridade de Compra</span><b>${d.cov<=14?'Comprar':d.cov<=30?'Atenção':'Normal'}</b><small>situação atual</small></div><div class="v2-item"><span>Próxima Compra</span><b>${d.qty?fmt(d.qty):'—'}</b><small>quantidade prevista</small></div></div></div>`}
detail('PP');pane.querySelectorAll('.v2-tab').forEach((b,n)=>b.onclick=()=>{if(n>2)return;pane.querySelectorAll('.v2-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');detail(types[n])});
}catch(err){pane.dataset.v2='';}}
function boot(){const p=document.querySelector('[data-pane="resumo"]');if(p)dashboard()}
new MutationObserver(boot).observe(document.getElementById('app'),{childList:true,subtree:true});[200,600,1200].forEach(x=>setTimeout(boot,x));
}