// Previsão e Planejamento — Caixas HUB
if(location.pathname.toLowerCase().startsWith('/admin')){
 const style=document.createElement('style');style.textContent=`
 .forecast-wrap{margin:14px 0}.forecast-head{display:flex;justify-content:space-between;align-items:end;gap:12px;margin-bottom:12px}.forecast-head h2{margin:0;color:#26343a;font-size:19px}.forecast-head p{margin:4px 0 0;color:#667d82;font-size:12px}.forecast-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.forecast-card{background:#fff;border:1px solid #dbe3e5;border-radius:16px;padding:17px;box-shadow:0 5px 18px #2638400a}.forecast-card h3{margin:0 0 12px;color:#26343a}.forecast-kpis{display:grid;grid-template-columns:1fr 1fr;gap:9px}.forecast-kpi{background:#f5f8f8;border-radius:10px;padding:10px}.forecast-kpi span{display:block;font-size:9px;text-transform:uppercase;color:#667d82;font-weight:800}.forecast-kpi b{display:block;margin-top:4px;font-size:16px;color:#26343a}.forecast-priority{display:inline-block;margin-top:11px;padding:6px 9px;border-radius:999px;font-size:10px;font-weight:900}.forecast-priority.normal{background:#e9f4ee;color:#39724d}.forecast-priority.atencao{background:#fff4df;color:#8a651d}.forecast-priority.comprar{background:#fde9e6;color:#9b4439}.forecast-note{margin-top:10px;font-size:11px;color:#667d82;line-height:1.45}@media(max-width:1050px){.forecast-grid{grid-template-columns:1fr}} `;document.head.appendChild(style);
 const dateBR=d=>d?new Date(d).toLocaleDateString('pt-BR'):'—';
 const addDays=(n)=>{if(!Number.isFinite(n))return null;const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+Math.max(0,Math.floor(n)));return d};
 async function build(){
  const pane=document.querySelector('[data-pane="resumo"]');if(!pane||pane.querySelector('.forecast-wrap'))return;
  try{
   const [r,e,i]=await Promise.all([fetch('https://c--09586474-253e-4035-b48c-481591adc286-prod.lovable.cloud/rest/v1/retiradas?select=*',{headers:{apikey:'sb_publishable_4zkSUbnHOH5kawdNM3d6lQ_xd5Do3bb'}}).then(x=>x.json()),fetch('https://c--09586474-253e-4035-b48c-481591adc286-prod.lovable.cloud/rest/v1/entradas_estoque?select=*',{headers:{apikey:'sb_publishable_4zkSUbnHOH5kawdNM3d6lQ_xd5Do3bb'}}).then(x=>x.json()),fetch('https://c--09586474-253e-4035-b48c-481591adc286-prod.lovable.cloud/rest/v1/inventarios?select=*&order=data_inventario.desc',{headers:{apikey:'sb_publishable_4zkSUbnHOH5kawdNM3d6lQ_xd5Do3bb'}}).then(x=>x.json())]);
   const now=new Date(),cut30=new Date(now-30*864e5),cut7=new Date(now-7*864e5),types=['PP','P','M'];let base={PP:1575,P:5550,M:1200},stock={...base};
   e.forEach(x=>{if(stock[x.tipo_caixa]!=null)stock[x.tipo_caixa]+=Number(x.total_caixas)||0});r.forEach(x=>{if(stock[x.tipo_caixa]!=null)stock[x.tipo_caixa]-=Number(x.total_caixas)||0});
   const inv=i[0];if(inv){const d=new Date(inv.data_inventario+'T23:59:59'),map={PP:'pp_contado',P:'p_contado',M:'m_contado'};types.forEach(t=>{const f=Number(inv[map[t]]);if(Number.isFinite(f)){stock[t]=f+e.filter(x=>x.tipo_caixa===t&&new Date(x.created_at)>d).reduce((s,x)=>s+(Number(x.total_caixas)||0),0)-r.filter(x=>x.tipo_caixa===t&&new Date(x.created_at)>d).reduce((s,x)=>s+(Number(x.total_caixas)||0),0)}})}
   const cards=types.map(t=>{const q30=r.filter(x=>x.tipo_caixa===t&&new Date(x.created_at)>=cut30).reduce((s,x)=>s+(Number(x.total_caixas)||0),0),q7=r.filter(x=>x.tipo_caixa===t&&new Date(x.created_at)>=cut7).reduce((s,x)=>s+(Number(x.total_caixas)||0),0),avg=q30/30,avg7=q7/7,days=avg>0?stock[t]/avg:Infinity,safety=avg*14,buy=Math.max(0,Math.ceil(avg*30+safety-stock[t])),trend=avg>0?((avg7-avg)/avg)*100:0,orderDays=avg>0?Math.max(0,(stock[t]-safety)/avg):Infinity,priority=days<=14?'comprar':days<=30?'atencao':'normal',label=priority==='comprar'?'COMPRAR':priority==='atencao'?'ATENÇÃO':'NORMAL';return `<article class="forecast-card"><h3>Caixa ${t}</h3><div class="forecast-kpis"><div class="forecast-kpi"><span>Cobertura</span><b>${Number.isFinite(days)?Math.floor(days)+' dias':'Sem consumo'}</b></div><div class="forecast-kpi"><span>Média 30 dias</span><b>${avg.toFixed(1)}/dia</b></div><div class="forecast-kpi"><span>Ruptura prevista</span><b>${dateBR(addDays(days))}</b></div><div class="forecast-kpi"><span>Comprar até</span><b>${dateBR(addDays(orderDays))}</b></div><div class="forecast-kpi"><span>Sugestão compra</span><b>${buy} un.</b></div><div class="forecast-kpi"><span>Tendência 7d</span><b>${trend>=0?'+':''}${trend.toFixed(0)}%</b></div></div><span class="forecast-priority ${priority}">${label}</span><div class="forecast-note">Previsão 30/60/90 dias: ${Math.ceil(avg*30)} / ${Math.ceil(avg*60)} / ${Math.ceil(avg*90)} caixas. Estoque de segurança considerado: 14 dias.</div></article>`}).join('');
   const box=document.createElement('div');box.className='forecast-wrap';box.innerHTML=`<div class="forecast-head"><div><h2>Previsão e Planejamento</h2><p>Projeções automáticas com base no consumo dos últimos 30 dias e tendência dos últimos 7 dias.</p></div></div><div class="forecast-grid">${cards}</div>`;pane.querySelector('.cards')?.after(box);
  }catch{}
 }
 const run=()=>[300,900,1800].forEach(ms=>setTimeout(build,ms));addEventListener('DOMContentLoaded',run,{once:true});run();
}