// Visual v3: altera apenas apresentação; não consulta nem modifica dados.
if(location.pathname.toLowerCase().startsWith('/admin')){
const s=document.createElement('style');s.textContent=`
:root{--v3:#087683;--v3d:#045563;--ink:#102b4d;--bg:#f4f8fa;--line:#dbe7ea}
body{background:var(--bg)!important;color:var(--ink)!important}
@media(min-width:951px){.admin-wrap{padding:0 16px 35px 226px!important;background:var(--bg)!important}.admin-shell{width:100%!important;max-width:none!important}.tabs{position:fixed!important;left:0!important;top:0!important;bottom:0!important;width:210px!important;height:100vh!important;background:linear-gradient(180deg,#087684,#045461)!important;padding:20px 11px!important;border:0!important;box-shadow:none!important;display:flex!important;flex-direction:column!important;gap:4px!important}.tabs:before{content:'◇  HUB'!important;display:block!important;color:#fff!important;font-size:27px!important;font-weight:900!important;padding:2px 10px 4px!important}.tabs:after{content:'CAIXAS E FITA GOMADA\A Controle de Estoque Inteligente'!important;white-space:pre!important;display:block!important;order:-1!important;color:#c9e9ec!important;font-size:9px!important;line-height:1.45!important;padding:47px 10px 14px!important;margin-bottom:-43px!important;border-bottom:1px solid #2a818b!important}.tab{position:relative!important;width:100%!important;text-align:left!important;color:#eefafa!important;background:transparent!important;border:0!important;border-radius:8px!important;padding:11px 10px 11px 40px!important;font-size:12px!important;font-weight:650!important}.tab:before{position:absolute!important;left:13px!important;top:50%!important;transform:translateY(-50%)!important;font-size:16px!important;color:#fff!important}.tab[data-tab="resumo"]:before{content:'⌂'!important}.tab[data-tab="retiradas"]:before{content:'↔'!important}.tab[data-tab="entradas"]:before{content:'▣'!important}.tab[data-tab="inventario"]:before{content:'▦'!important}.tab[data-tab="consumo"]:before{content:'▥'!important}.tab[data-tab="compras"]:before{content:'▤'!important}.tab[data-tab="relatorios"]:before{content:'▧'!important}.tab.active,.tab:hover{background:#0b8491!important;color:#fff!important}}
.admin-head{min-height:54px!important;margin:0 -16px 14px!important;padding:9px 18px!important;background:linear-gradient(90deg,#0a8592,#006673)!important;border:0!important;border-radius:0!important;box-shadow:none!important}.admin-kicker{display:none!important}.admin-head h1{font-size:16px!important;color:#fff!important;margin:0!important}.admin-head p{font-size:10px!important;color:#ddf2f4!important;margin:2px 0 0!important}.admin-actions{gap:7px!important}.ghost-btn{background:#fff!important;color:#08606c!important;border:0!important;border-radius:8px!important;padding:8px 11px!important;font-size:10px!important}
.cards{grid-template-columns:repeat(4,1fr)!important;gap:10px!important;margin-bottom:11px!important}.metric{min-height:90px!important;padding:15px!important;background:#fff!important;border:1px solid var(--line)!important;border-radius:10px!important;box-shadow:0 2px 9px #173d4708!important}.metric:before{display:none!important}.metric span{font-size:9px!important;color:#476571!important}.metric strong{font-size:27px!important;color:var(--ink)!important}.metric small{font-size:9px!important;color:#718790!important}.section-card{background:#fff!important;border:1px solid var(--line)!important;border-radius:10px!important;box-shadow:0 2px 9px #173d4708!important;padding:14px!important;margin-bottom:10px!important}.section-card h2{font-size:14px!important;color:var(--ink)!important}.hint{font-size:10px!important;color:#647d88!important}.table{font-size:10px!important}.table th{background:#edf4f6!important;color:#3e5d67!important;font-size:8px!important;padding:8px!important}.table td{padding:8px!important;color:#183746!important;border-color:#e5edef!important}.filters{gap:8px!important}.filters label{font-size:9px!important;color:#536f79!important}.filters input,.filters select{border:1px solid #d7e4e7!important;border-radius:7px!important;background:#fff!important}.export-btn{background:linear-gradient(90deg,#0a8290,#066773)!important;border-radius:7px!important}
.v3-welcome{margin:0 2px 12px}.v3-welcome h2{font-size:25px;line-height:1;margin:0;color:var(--ink)}.v3-welcome p{font-size:11px;color:#5d7681;margin:5px 0}.v3-shortcuts{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-bottom:10px}.v3-short{background:#fff;border:1px solid var(--line);border-radius:10px;padding:13px;display:flex;gap:10px;align-items:center}.v3-short i{width:34px;height:34px;display:grid;place-items:center;background:#e4f5f7;border-radius:8px;color:#087684;font-style:normal;font-size:18px}.v3-short b{display:block;font-size:11px;color:var(--ink)}.v3-short small{font-size:9px;color:#69808a}
@media(max-width:1100px){.cards,.v3-shortcuts{grid-template-columns:repeat(2,1fr)!important}}
`;document.head.appendChild(s);
function decorate(){const content=document.querySelector('#content');if(!content||content.hidden)return;const pane=content.querySelector('[data-pane="resumo"]');if(pane&&!pane.querySelector('.v3-welcome')){pane.insertAdjacentHTML('afterbegin','<div class="v3-welcome"><h2>Resumo Geral</h2><p>Visão completa do seu estoque e das próximas ações</p></div><div class="v3-shortcuts"><div class="v3-short"><i>▣</i><div><b>Estoque</b><small>Saldos atualizados</small></div></div><div class="v3-short"><i>▥</i><div><b>Consumo</b><small>Acompanhe a utilização</small></div></div><div class="v3-short"><i>▦</i><div><b>Inventário</b><small>Contagem física</small></div></div><div class="v3-short"><i>▤</i><div><b>Planejamento</b><small>Compras e relatórios</small></div></div></div>')}
const h=document.querySelector('.admin-head h1');if(h)h.textContent='Olá, Administrador!';const p=document.querySelector('.admin-head p');if(p)p.textContent='Aqui está o resumo do seu estoque e das próximas ações.'}
const root=document.getElementById('app');if(root)new MutationObserver(decorate).observe(root,{subtree:true,childList:true,attributes:true});[0,300,800,1600].forEach(t=>setTimeout(decorate,t));
}