"use client";
import {useEffect,useState} from "react";
import {Box,Boxes,PackageOpen,History,AlertTriangle} from "lucide-react";
import {KpiCard} from "@/components/ui/kpi-card";
import {supabase} from "@/lib/supabase";
import {RecentWithdrawals} from "./recent-withdrawals";
const BASE={PP:1575,P:5550,M:1200};const LOW={PP:250,P:500,M:250}; type Kind=keyof typeof BASE;
type W={tipo_caixa:Kind;total_caixas:number;created_at:string;responsavel?:string;fardos?:number}; type E=W;
type I={data_inventario:string;created_at:string;pp_contado:number;p_contado:number;m_contado:number};
export function Dashboard(){const[rows,setRows]=useState<W[]>([]),[entries,setEntries]=useState<E[]>([]),[inv,setInv]=useState<I|null>(null),[loading,setLoading]=useState(true);
useEffect(()=>{if(!supabase){setLoading(false);return}Promise.all([supabase.from("retiradas").select("tipo_caixa,total_caixas,created_at,responsavel,fardos").order("created_at",{ascending:false}),supabase.from("entradas_estoque").select("tipo_caixa,total_caixas,created_at"),supabase.from("inventarios").select("data_inventario,created_at,pp_contado,p_contado,m_contado").order("data_inventario",{ascending:false}).order("created_at",{ascending:false}).limit(1)]).then(([w,e,i])=>{setRows((w.data||[]) as W[]);setEntries((e.data||[]) as E[]);setInv((i.data?.[0]||null) as I|null);setLoading(false)})},[]);
const balance=(k:Kind)=>{let value=BASE[k]+entries.filter(e=>e.tipo_caixa===k).reduce((s,e)=>s+Number(e.total_caixas||0),0)-rows.filter(r=>r.tipo_caixa===k).reduce((s,r)=>s+Number(r.total_caixas||0),0);if(inv){const d=new Date(inv.data_inventario+"T23:59:59");const key={PP:"pp_contado",P:"p_contado",M:"m_contado"}[k] as "pp_contado"|"p_contado"|"m_contado";const physical=Number(inv[key]);if(Number.isFinite(physical)){const after=(x:string)=>new Date(x)>d;value=physical+entries.filter(e=>e.tipo_caixa===k&&after(e.created_at)).reduce((s,e)=>s+Number(e.total_caixas||0),0)-rows.filter(r=>r.tipo_caixa===k&&after(r.created_at)).reduce((s,r)=>s+Number(r.total_caixas||0),0)}}return value};
const alerts=(["PP","P","M"] as Kind[]).map(k=>({k,value:balance(k)})).filter(x=>x.value<=LOW[x.k]);return <>{!loading&&alerts.length>0&&<div className="mb-5 flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-900"><AlertTriangle className="mt-0.5 shrink-0" size={20}/><div><p className="font-bold">Atenção ao estoque</p><p className="mt-1 text-sm">{alerts.map(x=>`Caixa ${x.k}: ${x.value} caixas`).join(" • ")}</p></div></div>}<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard title="Estoque PP" value={loading?"…":balance("PP")} detail="saldo atual" Icon={PackageOpen}/><KpiCard title="Estoque P" value={loading?"…":balance("P")} detail="saldo atual" Icon={Box}/><KpiCard title="Estoque M" value={loading?"…":balance("M")} detail="saldo atual" Icon={Boxes}/><KpiCard title="Retiradas" value={loading?"…":rows.length} detail="movimentações registradas" Icon={History}/></section><RecentWithdrawals rows={rows}/></>}