"use client";
import {useEffect,useState} from "react";
import {Box,Boxes,PackageOpen,History} from "lucide-react";
import {KpiCard} from "@/components/ui/kpi-card";
import {supabase} from "@/lib/supabase";
import {RecentWithdrawals} from "./recent-withdrawals";
import {Card,CardContent} from "@/components/ui/card";
const BASE={PP:1575,P:5550,M:1200}; type Kind=keyof typeof BASE;
type W={tipo_caixa:Kind;total_caixas:number;created_at:string;responsavel?:string;fardos?:number}; type E=W;
type I={data_inventario:string;created_at:string;pp_contado:number;p_contado:number;m_contado:number};
export function Dashboard(){const[rows,setRows]=useState<W[]>([]),[entries,setEntries]=useState<E[]>([]),[inv,setInv]=useState<I|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
useEffect(()=>{if(!supabase){setLoading(false);return}Promise.all([supabase.from("retiradas").select("tipo_caixa,total_caixas,created_at,responsavel,fardos").order("created_at",{ascending:false}),supabase.from("entradas_estoque").select("tipo_caixa,total_caixas,created_at"),supabase.from("inventarios").select("data_inventario,created_at,pp_contado,p_contado,m_contado").order("data_inventario",{ascending:false}).order("created_at",{ascending:false}).limit(1)]).then(([w,e,i])=>{if(w.error||e.error||i.error){setError("Não foi possível carregar os dados do painel.");setLoading(false);return}setRows((w.data||[]) as W[]);setEntries((e.data||[]) as E[]);setInv((i.data?.[0]||null) as I|null);setLoading(false)}).catch(()=>{setError("Não foi possível carregar os dados do painel.");setLoading(false)})},[]);
const balance=(k:Kind)=>{let value=BASE[k]+entries.filter(e=>e.tipo_caixa===k).reduce((s,e)=>s+Number(e.total_caixas||0),0)-rows.filter(r=>r.tipo_caixa===k).reduce((s,r)=>s+Number(r.total_caixas||0),0);if(inv){const d=new Date(inv.data_inventario+"T23:59:59");const key={PP:"pp_contado",P:"p_contado",M:"m_contado"}[k] as "pp_contado"|"p_contado"|"m_contado";const physical=Number(inv[key]);if(Number.isFinite(physical)){const after=(x:string)=>new Date(x)>d;value=physical+entries.filter(e=>e.tipo_caixa===k&&after(e.created_at)).reduce((s,e)=>s+Number(e.total_caixas||0),0)-rows.filter(r=>r.tipo_caixa===k&&after(r.created_at)).reduce((s,r)=>s+Number(r.total_caixas||0),0)}}return value};
return <>{error&&<div className="mb-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-700">{error} Nenhum saldo foi recalculado nesta tela.</div>}<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard title="Estoque PP" value={loading?"…":error?"—":balance("PP")} detail="caixas disponíveis" Icon={PackageOpen} tone="medium"/><KpiCard title="Estoque P" value={loading?"…":error?"—":balance("P")} detail="caixas disponíveis" Icon={Box} tone="soft"/><KpiCard title="Estoque M" value={loading?"…":error?"—":balance("M")} detail="caixas disponíveis" Icon={Boxes} tone="soft"/><KpiCard title="Estoque total" value={loading?"…":error?"—":balance("PP")+balance("P")+balance("M")} detail="caixas disponíveis" Icon={History} tone="dark"/></section>{!loading&&!error&&<RecentWithdrawals rows={rows}/>}{!loading&&!error&&<Card className="mt-6 overflow-hidden"><CardContent className="p-0"><div className="border-b p-5 lg:p-6"><h3 className="font-bold text-gray-900">Últimas movimentações</h3><p className="mt-1 text-sm text-[var(--muted)]">Entradas e retiradas mais recentes do estoque de caixas</p></div><div className="divide-y">{[...rows.map(r=>({date:r.created_at,type:"Retirada",kind:r.tipo_caixa,qty:Number(r.total_caixas||0),who:r.responsavel||"—"})),...entries.map(e=>({date:e.created_at,type:"Entrada",kind:e.tipo_caixa,qty:Number(e.total_caixas||0),who:"Estoque"}))].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime()).slice(0,8).map((x,i)=><div key={`${x.type}-${x.date}-${i}`} className="flex flex-wrap items-center justify-between gap-3 px-5 py-3.5 hover:bg-gray-50/70 lg:px-6"><div><p className="text-sm font-semibold text-gray-900">{x.type} • Caixa {x.kind}</p><p className="mt-0.5 text-xs text-[var(--muted)]">{new Date(x.date).toLocaleString("pt-BR")} • {x.who}</p></div><span className="text-sm font-bold text-gray-700">{x.type==="Entrada"?"+":"-"}{x.qty} caixas</span></div>)}</div></CardContent></Card>}</>}