"use client";
import {useEffect,useRef,useState} from "react";
const KEY="hub-banner-image";
export function HeroBanner(){
 const [src,setSrc]=useState("/approved-boxes-tape.png");
 useEffect(()=>{try{const saved=localStorage.getItem(KEY);if(saved)setSrc(saved)}catch{}},[]);
 return <section className="hub-hero relative mb-7 min-h-[132px] overflow-hidden rounded-[20px] border border-[var(--border)] px-5 py-4 sm:px-7"><div className="hub-wave hub-wave-one"/><div className="hub-wave hub-wave-two"/><div className="relative z-10 grid min-h-[96px] items-center gap-5 lg:grid-cols-[1.7fr_.85fr_150px]"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-[var(--primary)]">Painel administrativo</p><h2 className="text-2xl font-bold tracking-tight text-[#101c2d]">Visão geral</h2><p className="mt-2 text-sm font-medium text-[#49636c] sm:text-lg">Cada caixa, cada pedido, cada pessoa: juntos fazemos o HUB acontecer.</p></div><div className="hero-quote hidden border-l-[3px] border-[#526f78] pl-7 lg:block"><p>ORGANIZAÇÃO<br/>DE HOJE,<br/><strong>RESULTADOS<br/>DE AMANHÃ.</strong></p></div><div className="hero-boxes approved-photo-wrap hidden lg:block" aria-hidden="true"><img src={src} alt="" className={src==="/approved-boxes-tape.png"?"approved-photo-exact approved-photo-default":"approved-photo-exact approved-photo-custom"}/></div></div></section>
}
export function BannerImageSettings(){
 const input=useRef<HTMLInputElement>(null);const [preview,setPreview]=useState("/approved-boxes-tape.png");const [pending,setPending]=useState<string|null>(null);const [msg,setMsg]=useState("");
 useEffect(()=>{try{const saved=localStorage.getItem(KEY);if(saved)setPreview(saved)}catch{}},[]);
 const choose=(f?:File)=>{if(!f)return;if(!f.type.startsWith("image/")){setMsg("Selecione um arquivo de imagem.");return}if(f.size>4*1024*1024){setMsg("A imagem deve ter no máximo 4 MB.");return}const r=new FileReader();r.onload=()=>{const s=String(r.result);setPending(s);setPreview(s);setMsg("Pré-visualização pronta. Clique em Salvar imagem.")};r.readAsDataURL(f)};
 const save=()=>{if(!pending)return;try{localStorage.setItem(KEY,pending);setPending(null);setMsg("Imagem salva. Volte ao Início para visualizar.")}catch{setMsg("Não foi possível salvar. Tente uma imagem menor.")}};
 const restore=()=>{try{localStorage.removeItem(KEY)}catch{};setPending(null);setPreview("/approved-boxes-tape.png");setMsg("Imagem padrão restaurada.")};
 return <div><div className="mb-4 overflow-hidden rounded-2xl border bg-[var(--background)] p-3"><div className="grid h-40 place-items-center overflow-hidden rounded-xl bg-white"><img src={preview} alt="Pré-visualização do banner" className="max-h-full max-w-full object-contain"/></div></div><input ref={input} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>choose(e.target.files?.[0])}/><div className="flex flex-wrap gap-3"><button type="button" onClick={()=>input.current?.click()} className="rounded-xl bg-[var(--primary)] px-4 py-2.5 text-sm font-semibold text-white">Escolher imagem</button><button type="button" disabled={!pending} onClick={save} className="rounded-xl bg-[var(--primary-dark)] px-4 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">Salvar imagem</button><button type="button" onClick={restore} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold text-gray-700">Restaurar imagem padrão</button></div>{msg&&<p className="mt-3 text-sm text-[var(--muted)]">{msg}</p>}<p className="mt-3 text-xs leading-5 text-[var(--muted)]">Formatos: PNG, JPG ou WebP. Máximo 4 MB. A imagem é ajustada automaticamente sem alterar os dados do sistema.</p></div>
}